### ISSUE TITLE
Confusion over `keystore` parameter

### ISSUE THREAD

**Issue by ACMCMC** [victorbnl/build-signed-apk#1]
Right now, the documentation doesn't make it very clear that the `keystore` parameter on the GitHub action should be _the contents of the key file_.

It is easy to get confused, and think that it is instead the _path to the key file_, encoded in base64.

I believe that it would be better to have two separate inputs:
- `keystore_b64`: The current `keystore` input. The _contents_ of the keystore file, in base64.
- `keystore_file`: A path to the keystore file. It should not be encoded in base64.

The user should only provide one of the parameters, and it will get used to sign the APK.

**Comment by marie-bnl** [comment]
A user should of course never commit a keystore file on the repository ; therefore I don't think a "keystore_file" parameter containing a path would be relevant. However I agree to rename keystore in keystore_b64

**Comment by ACMCMC** [comment]
I don't believe a keystore file should _never_ be commited to a repository. I can think of two examples of use cases:
- Users that do not mind about their keys being publicly distributed (for example, for personal projects in the `hello-world` style).
- Repositories that are private (it's up to the user to decide if they want to take the responsibility of ensuring that no unauthorised user accesses the repo).

Moreover, the keystore file is encrypted (see [this link](https://stackoverflow.com/a/56116822/5704763)). So it's another additional measure of security.

All in all, I believe that the user should be given the ability to _take the risk_ of getting their private keys publicly shared. If they decide that they want to take that risk, we shouldn't make this choice in their place.

However, I do think that it is a good idea to include a warning about the potential security threat of committing the keystore file to a repository. What do you think about that?

**Comment by marie-bnl** [comment]
Solved by #2
