### ISSUE TITLE
Licences agreement error

### ISSUE THREAD

**Issue by marie-bnl** [victorbnl/build-signed-apk#6]
Thanks for the update. Now I'm getting this error:
```
What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Failed to install the following Android SDK packages as some licences have not been accepted.
     build-tools;34.0.0-rc3 Android SDK Build-Tools 34-rc3
  To build this project, accept the SDK license agreements and install the missing components using the Android Studio SDK Manager.
  All licenses can be accepted using the sdkmanager command line tool:
  sdkmanager.bat --licenses
```

_Originally posted by @acolombo25 in https://github.com/victorbnl/build-signed-apk/issues/5#issuecomment-1645735865_

**Comment by marie-bnl** [comment]
I can’t reproduce it. Would you mind sharing your project (in private via e-mail if you want)?

**Comment by acolombo11** [comment]
> 

https://github.com/acolombo25/lock-screen

**Comment by marie-bnl** [comment]
Now it should work (fixed by https://github.com/victorbnl/build-signed-apk/commit/e086f3dbc47baede55600371b8e33b72b8288433).

**Comment by acolombo11** [comment]
It looks like there's still a little problem after the build finished
```
> Task :app:assembleRelease

BUILD SUCCESSFUL in 12s
38 actionable tasks: 2 executed, 36 up-to-date
/home/runner/work/_temp/fdffee6c-3446-4e23-ae4e-a278fb2e0713.sh: line 7: R!: command not found
Error: Process completed with exit code 127.
```

**Comment by marie-bnl** [comment]
That means the licenses issue is fixed; creating a new issue.
